### PR TITLE
Remove deadlinks from merchants.yml

### PR DESCRIPTION
**Pull request by BTBTravis**
Removes dead links mentioned in #8 . Plus a few I found combing thought the data. I basically stripped the .yml down to only the urls then open chunks of 50 at a time in the browser and just tabbed through them looking for dead or deactivated sites. 

Stumbled onto some pretty cool sites along the way!

Cheers

### CODE REVIEW

**Comment by BTBTravis** [comment]
Dead links: 

https://www.etsy.com/no-en/shop/CryptoCatDad
http://www.naturkost-leiferde.de/
https://alcoyoung.com/
https://coinspec.net/
https://geckovapesco.com/

**Comment by corroded** [comment]
Thanks for this! You beat me by a few minutes! I'm testing out a script I found that combs through all the URLs so we don't always have to go click each one.

**Comment by BTBTravis** [comment]
Nice! That sounds challenging as lot of them don't return 404 errors but deactivated Shopify pages and such. I'll check back in a few days for more issues. 

🍻Cheers!

**Comment by corroded** [comment]
Nah just made a simple script that outputs the status code. I still manually check the ones that don't return 200s. The deactivated Shopify pages return a `402` (Payment required) so not a problem since I still get to check them :)

**Pull request merged**
